# 服务器前置任务(ubuntu使用)
- name: phabricator
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt-get -y install python


# 核心任务
- name: phabricator
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - {role: common,tags: "common"}
    - {role: mysql,tags: "mysql"}
    - {role: phabricator,tags: "phabricator"}
    - {role: docker,tags: "docker"}
    - {role: docker_phpmyadmin,tags: "docker_phpmyadmin"}