# 核心任务
- name: phabricator
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, tags: "role_apache"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_phpmyadmin, tags: "role_phpmyadmin"}
    - {role: phabricator, tags: "phabricator"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_preend, preend_certbot: True, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}